name: "F5 BIG-IP Telemetry (AST+Prometheus)"
version: "0.9.6-10-debug"
slug: "f5_bigip_telemetry_aio"
description: "F5 OTel Collector + Built-in Prometheus."
url: "https://github.com/raphael1688dev/addon-f5-ast"
arch:
  - amd64
startup: services
options:
  f5_host: "192.168.1.245"
  f5_username: "admin"
  f5_password: "admin"
  collection_interval: "30s"
  insecure_skip_verify: true
  log_level: "info"

  # --- Modules ---
  enable_system: true
  enable_ltm: true
  enable_apm: true
  enable_asm: true
  enable_gtm: true
  enable_afm: true
  
  enable_net: false
  enable_pem: false
  enable_avr: false
  enable_vcmp: false

schema:
  f5_host: str
  f5_username: str
  f5_password: password
  collection_interval: str
  insecure_skip_verify: bool
  log_level: str
  
  enable_system: bool
  enable_ltm: bool
  enable_net: bool
  enable_asm: bool
  enable_gtm: bool
  enable_apm: bool
  enable_afm: bool
  enable_pem: bool
  enable_avr: bool
  enable_vcmp: bool

ports:
  8888/tcp: 8888  # OTel Metrics
  9090/tcp: 9090  # Prometheus UI / Grafana Source
